// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnIVr1Fe9HUxdRByEjaiaZWURyu3BC35U',
    appId: '1:992806521648:web:a3d0842e5f838c5f3296f5',
    messagingSenderId: '992806521648',
    projectId: 'mahsolek-8417b',
    authDomain: 'mahsolek-8417b.firebaseapp.com',
    databaseURL: 'https://mahsolek-8417b-default-rtdb.firebaseio.com',
    storageBucket: 'mahsolek-8417b.firebasestorage.app',
    measurementId: 'G-BSD6VM8R6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWUyA6YRSSPV8WatzlbxOBqznN1LUHBNI',
    appId: '1:611277588462:android:dce16489549a9e57a5b0ff',
    messagingSenderId: '611277588462',
    projectId: 'testing-79c4f',
    databaseURL: 'https://testing-79c4f-default-rtdb.firebaseio.com',
    storageBucket: 'testing-79c4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZTLOaz1w0V-98xc9HHMctid8MsxXI_Q',
    appId: '1:992806521648:ios:7e7d4fe7a9b608403296f5',
    messagingSenderId: '992806521648',
    projectId: 'mahsolek-8417b',
    databaseURL: 'https://mahsolek-8417b-default-rtdb.firebaseio.com',
    storageBucket: 'mahsolek-8417b.firebasestorage.app',
    androidClientId: '992806521648-2p9185mjpcl68cmm6diffoju04c6dpah.apps.googleusercontent.com',
    iosClientId: '992806521648-p3nd5s63sflm0l2i0rdiq27dr16r9ifg.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmersAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYC5uuMut4DPcHi7ul0WjKuH_qyOjflls',
    appId: '1:611277588462:web:7aa39f83db7baa5aa5b0ff',
    messagingSenderId: '611277588462',
    projectId: 'testing-79c4f',
    authDomain: 'testing-79c4f.firebaseapp.com',
    databaseURL: 'https://testing-79c4f-default-rtdb.firebaseio.com',
    storageBucket: 'testing-79c4f.firebasestorage.app',
    measurementId: 'G-C9WSLY0Z1L',
  );

}