// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYC5uuMut4DPcHi7ul0WjKuH_qyOjflls',
    appId: '1:611277588462:web:638aaf7c5cc60e75a5b0ff',
    messagingSenderId: '611277588462',
    projectId: 'testing-79c4f',
    authDomain: 'testing-79c4f.firebaseapp.com',
    databaseURL: 'https://testing-79c4f-default-rtdb.firebaseio.com',
    storageBucket: 'testing-79c4f.firebasestorage.app',
    measurementId: 'G-G61E2YQJG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWUyA6YRSSPV8WatzlbxOBqznN1LUHBNI',
    appId: '1:611277588462:android:dce16489549a9e57a5b0ff',
    messagingSenderId: '611277588462',
    projectId: 'testing-79c4f',
    databaseURL: 'https://testing-79c4f-default-rtdb.firebaseio.com',
    storageBucket: 'testing-79c4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwEFt79Yd01rCL_FfdJGf46uQjtKQ6JF4',
    appId: '1:650859289991:ios:cf92082adacfc6d44f0722',
    messagingSenderId: '650859289991',
    projectId: 'login-system-86de6',
    storageBucket: 'login-system-86de6.firebasestorage.app',
    iosBundleId: 'com.example.farmersAdmin',
    databaseURL: 'https://login-system-86de6-default-rtdb.firebaseio.com', // 👈 ADD THIS
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYC5uuMut4DPcHi7ul0WjKuH_qyOjflls',
    appId: '1:611277588462:web:7aa39f83db7baa5aa5b0ff',
    messagingSenderId: '611277588462',
    projectId: 'testing-79c4f',
    authDomain: 'testing-79c4f.firebaseapp.com',
    databaseURL: 'https://testing-79c4f-default-rtdb.firebaseio.com',
    storageBucket: 'testing-79c4f.firebasestorage.app',
    measurementId: 'G-C9WSLY0Z1L',
  );

}